name:                dockeybay
version:             0.1.0.0
github:              "ssisksl77/dockeybay"
license:             BSD3
author:              "Younghwan Nam"
maintainer:          "ssisksl77@gmail.com"
copyright:           "Younghwan Nam"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/dockeybay#readme>

dependencies:
- base >= 4.7 && < 5
- directory
- split


library:
  source-dirs: src

executables:
  dockeybay-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dockeybay

tests:
  dockeybay-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dockeybay
